resources:
  - ../../controller
  - ../../dashboard
  - ../../series-tracker
  - ../../kernel-disk

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never

images:
  - name: controller-image
    newName: controller-image-local:latest
  - name: web-dashboard-image
    newName: web-dashboard-local:latest
  - name: series-tracker-image
    newName: series-tracker-local:latest
