apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-mgmt
  template:
    metadata:
      labels:
        app: db-mgmt
    spec:
      containers:
      - name: db-mgmt-local
        image: db-mgmt-local:latest
        imagePullPolicy: Never
        command: ["db-mgmt", "migrate", "/migrations"]
      restartPolicy: Never
